src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ActivityDateTime__c</fullName>
        <description>ActivityDateTime</description>
        <inlineHelpText>ActivityDateTime</inlineHelpText>
        <label>ActivityDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>Field is used to map program from lead to a customer request.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Programs</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ActivityDateTime__c</fullName>
        <description>ActivityDateTime</description>
        <inlineHelpText>ActivityDateTime</inlineHelpText>
        <label>ActivityDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date of Birth</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email2__c</fullName>
        <description>This field is created for the secondary email and is replacing student email fields</description>
        <label>Email2</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HomePhone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>InsertTime__c</fullName>
        <description>this is captured to differentiate between incoming and exiting leads.</description>
        <label>DCBatchInsertTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Market</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Phone__c</fullName>
        <description>This is to store a secondary number</description>
        <label>Other Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product to which lead belongs</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>Program to which Lead belongs</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Programs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>RequestType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>RequestType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesOffice__c</fullName>
        <label>SalesOffice</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Market__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>SalesOffice</valueSetName>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <businessProcess>Customer</businessProcess>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadsApiHandler.cls
@RestResource(urlMapping='/Lead/*')
global class LeadsApiHandler
{
    @HttpPost
    global static Boolean CreateBulkLead(LeadWrapperClass[] leadWrapperObj)
    {
        boolean success=false;
        List<Lead> leads=new List<Lead>();
        Datetime nowdatetime=datetime.now();
        try{
            for(LeadWrapperClass leadWrapper : leadWrapperObj)
            {
                /*if (AllowLead(leadWrapper)==false)
                {
                    continue;
                }*/
                Lead newLead=new Lead();
                newLead.FirstName=leadWrapper.FirstName;
                newLead.LastName=leadWrapper.LastName;
                newLead.street=leadWrapper.street;
                newLead.City=leadWrapper.City;

                newLead.PostalCode=leadWrapper.PostalCode;
                newLead.State=leadWrapper.State;
                // newLead.Country=leadWrapper.Country;
                // newLead.CountryCode=leadWrapper.CountryCode;   //some deployment issues..need to check once

                newLead.MobilePhone=leadWrapper.MobilePhone;
                newLead.Other_Phone__c=leadWrapper.OtherPhone;
                newLead.HomePhone__c=leadWrapper.LandlinePhone;

                newLead.DOB__c=leadWrapper.DOB;
                newLead.Email=leadWrapper.StudentEmail1;
                newLead.Email2__c=leadWrapper.StudentEmail2;
               // newLead.Parent_Email__c=leadWrapper.ParentEmail;
                //newLead.Invoice_Email__c=leadWrapper.InvoiceEmail;
                newLead.Region__c=leadWrapper.Region ;
                //newLead.Activity__c=LeadWrapper.Activity;
                newLead.RequestType__c=LeadWrapper.Activity;

                newLead.Product__c=LeadWrapper.Product;
                newLead.Program__c=leadWrapper.Program;
                newLead.Market__c=leadWrapper.MarketCode;
                //newLead.RecordTypeId=GetRecordTypeOnMarketCode(leadWrapper.MarketCode);
                newLead.InsertTime__c=nowdatetime;
                newLead.SalesOffice__c = 'DEB';
                newLead.ActivityDateTime__c=LeadWrapper.ActivityDate;//this field is being used in order to keep track of latest activity done by same customer.
                leads.add(newLead);
            }
            if(leads.size()>0)
            {
                success=HandleIncomingLeads(leads);
            }
            else
            {
            }}catch (Exception e){
            return false;
        }
        return success;
    }

    //It finds out the record type based on marketcode
   /* public static Id GetRecordTypeOnMarketCode(string marketCode)
    {
        recordtype rType=[select id from recordtype where name=:marketCode and IsActive=true and SObjectType='Lead'];
        return rType.Id;
    }*/
    //This function checks if an incoming Customer Request can be imported into SF or not.
    public static boolean AllowLead(LeadWrapperClass leadWrapperObj)
    {
        if (leadWrapperObj.StudentEmail1.EndsWith('@ef.com')
                ||leadWrapperObj.StudentEmail1.Contains('test')
                ||leadWrapperObj.StudentEmail2.EndsWith('@ef.com')
                ||leadWrapperObj.StudentEmail2.Contains('test')
                ||leadWrapperObj.InvoiceEmail.EndsWith('@ef.com')
                ||leadWrapperObj.InvoiceEmail.Contains('test')
                ||leadWrapperObj.ParentEmail.EndsWith('@ef.com')
                ||leadWrapperObj.ParentEmail.Contains('test'))
        {
            return false;
        }
        else
                return true;
    }
    //This function Processes the incoming Leads.
    public static boolean HandleIncomingLeads(List<Lead> incomingLeads)
    {
        boolean success=false;
        //we can add one dummy lead if there is only one incoming lead just to avoid dc api call.
        //Lead newLead=new Lead();
        // newLead.FirstName='DEMO';
        //newLead.LastName='DEMO LAst';
        //incomingLeads.add(newLead);
        success=SObjectUnitOfWork.executeInsertLeads(incomingLeads);
        if (success)
        {
            if (incomingLeads.size()==1)//if there is only one lead insert DC Search plugin does not get hit, so in this case we are explicitly calling search api.
            {
                Lead lead=incomingLeads[0];
                dupcheck.dc3Api api = new dupcheck.dc3Api();
                api.doSearch(lead);
            }
        }
        else
        {
        }
        return success;
    }
}