src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IsDupe__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once it is identified as Dupe, this flag will be set for further processing</description>
        <label>Is Dupe</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReadyForRanking__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Once the dupe check process is completed, this flag will be set</description>
        <label>Ready For Ranking</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DCBusinessFlowHelper.cls
/**
 * Created by shravan.boddula on 9/6/2017.
 */

public with sharing class DCBusinessFlowHelper {
    //notify ranking
    public static void notifyForRanking(Lead sourceLead) {
        try {
            system.debug('********** hitting ranking');
            system.debug('***** is dupe'+sourceLead.IsDupe__c);
            if (sourceLead.IsDupe__c == false) {
                sourceLead.ReadyForRanking__c = true;
                system.debug('********** hitting ranking inside if');
            }
            system.debug('***** ready for ranking'+sourceLead.ReadyForRanking__c);
            system.debug('********** final dml');
            SObjectUnitOfWork.executeUpdateLeads(new List<Lead>{sourceLead});

        } catch (Exception ex) {
            system.debug('exception in notifyranking');
            ExceptionHandler.errorLog(ex.getMessage(),
                    ex.getStackTraceString(), 'DCBusinessFlowHelper', 'notifyForRanking', '');
        }
    }

}