src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>Program to which Lead belongs</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Programs</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MarketProgramLevelSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Checks the Market and Program of Lead records.</description>
    <label>MarketProgramLevelSetting</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Programs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>this is to capture the active opportunity</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Referred for Personal task</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TaskSettings__mdt.object
<CustomObject>
    <description>This will help in mapping Customer Request to Tasks And Tasks to Tasks</description>
    <fields>
        <fullName>CanCloseManually__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Can the task be closed manually</description>
        <label>CanCloseManually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CanCreateMannually__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CanCreateMannually</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CreateCallType__c</fullName>
        <description>This will tell which task we can create  for which Activity/Task
values will be seperated by &apos;|&apos;</description>
        <label>CreateCallType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ForClosedCallTypes__c</fullName>
        <description>If all the call type tasks for customer is closed then use create tasks based on this field</description>
        <label>ForClosedCallTypes</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Weather thee following record is active or not</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCallType__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCallType</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTaskPerCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This will define weather multiple one customer can have multiple tasks</description>
        <label>IsTaskPerCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>This should be same as ENUM name as we are mapping ENUM name to this field</description>
        <label>Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>No__c</fullName>
        <description>This Number is same as ENUM number in Code ,Make sure if you change anything in this metadata you need to change in apex code as well REF: ENUM order we are depending on ENUM order as ENUM order in code and rows in this settings are same</description>
        <label>No</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RULE__c</fullName>
        <description>this will be custom label name which contains rule for executing the task/Activity</description>
        <label>RULE</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleForActivity__c</fullName>
        <description>This will define what rules to be applied while creating/Updating Task from activity</description>
        <label>RuleForActivity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleForTask__c</fullName>
        <description>This will tell what rules to be applied while creating/Updating Tasks from Task(For user only this we are not reading in code we have rules defined in code but we check if this column is empty or not while applying rule)</description>
        <label>RuleForTask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskGroup__c</fullName>
        <description>Group of Tasks separated by &apos;|&apos;</description>
        <label>TaskGroup</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaskSubject__c</fullName>
        <description>This will be subject of the task while creating</description>
        <label>TaskSubject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the task setting</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Customer Request</fullName>
                    <default>true</default>
                    <label>Customer Request</label>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpdateCallType__c</fullName>
        <description>Update the call type tasks if we have any open call type tasks</description>
        <label>UpdateCallType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Task Setting</label>
    <pluralLabel>Task Settings</pluralLabel>
</CustomObject>

src/classes/TasksHelperTest.cls
/**
 * Created by thejasvi.a on 8/10/2017.
 */

@isTest(SeeAllData=false)
private class TasksHelperTest {

    static testMethod void testIncomingLeads() {
        //  List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');
        Test.startTest();
        system.runAs(TestDataUtil.createUserRecord()) {
         List<id> oppId= new List<id>();
            List<string> requestTypeValues = new List<string>();
            List<lead> leadListExisting = new list<lead>();
            List<lead> leadList = new list<lead>();
            List<TaskSettings__mdt> customMetadata = [
                    SELECT CanCloseManually__c,CanCreateMannually__c,
                CreateCallType__c,ForClosedCallTypes__c,IsActive__c,RuleForTask__c,
                IsCallType__c,IsTaskPerCustomer__c,Name__c,RuleForActivity__c,
                No__c,RULE__c,TaskGroup__c,Type__c,UpdateCallType__c,TaskSubject__c
                    FROM TaskSettings__mdt order by No__c];

            for (TaskSettings__mdt values: customMetadata) {
                requestTypeValues.add(values.name__c);
            }

            system.debug('>>>>>values' + requestTypeValues);
            List<id> testids= new List<id>();
            List<lead> insertLead=new List<Lead>();
            for (integer i = 0; i <= 6; i++) {
              Lead leadRecord = new Lead();
                system.debug('>>>>>size' + requestTypeValues.size());
                leadRecord = TestDataUtil.DynamicinsertNewLeadRecords('ABC'+i, 'lastname'+i, 'city'+i, 'street'+i, 'karnataka'+i, ' postalcode'+i, '123456'+i, '1234567890'+i, '1234567890'+i, '12345'+i, 'u@gmail.com'+i, 'pppp@gmail.com'+i, 'region'+i, requestTypeValues[i], System.today());
                system.debug('leadList>>>>'+leadList);
                leadList.add(leadRecord);
                
            }
            insert leadList;
            system.debug('>>>>>>>leadList'+leadList);
            List<id> leadId= new List<id>();
            for(lead leadrec :leadList)
            {
            leadId.add(leadrec.id);
            }
            List<Event> eventList =[SELECT Type, WhoId FROM event where whoid in: leadId];
            system.debug('event >>>>'+eventList );

             List<Database.LeadConvert> leadConverts =new List<Database.LeadConvert>();
                for(Lead leadRecord : leadList){                    
                    
                        Database.LeadConvert leadConversion = new database.LeadConvert();
                        leadConversion.setLeadId(leadRecord.Id);
                        leadConversion.setConvertedStatus(System.Label.LeadStageConverted);
                        leadConversion.setOpportunityName(leadRecord.FirstName + ' ' + leadRecord.LastName);
                        leadConverts.add(leadConversion);
                    
                }
                
              if(!leadConverts.isEmpty()){
              system.debug('inside conversion');
                    for(Integer i = 0; i <= leadConverts.size()/100 ; i++){
                        list<Database.LeadConvert> tempList = new list<Database.LeadConvert>();
                        Integer startIndex = i*100;
                        Integer endIndex = ((startIndex+100) < leadConverts.size()) ? startIndex+100: leadConverts.size();
                        for(Integer j=startIndex;j<endIndex;j++){
                            tempList.add(leadConverts[j]);
                        }
                        Database.LeadConvertResult[] leadConvertedList = Database.convertLead(tempList, false);
                        //system.debug('>>>leadConvertedList '+leadConvertedList.getOpportunityId );
                         for(Database.LeadConvertResult lcr : leadConvertedList ){
                         System.assert(lcr.isSuccess());
                         system.debug('lcr>>>'+lcr.getOpportunityId());                        
                         oppId.add(lcr.getOpportunityId());
                            }                        
                    }
                }
        List<Id> oppsId= new List<Id>();
        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE id in: oppId];
        for(opportunity opp:opQuery) {
        oppsId.add(opp.id);        
        }
        system.debug('My ids are@@@@@'+oppsId);
        List<Task> taskList =[SELECT Type, WhatId, whoid FROM task where whatid in : oppsId order by type];
        system.debug('>>>>opQuery'+opQuery);
        system.debug('>>>>taskListtej'+taskList );
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
        system.assertEquals('MCR', taskList[0].Type);
        system.assertEquals('SPQ', taskList[1].Type);
        system.assertEquals('SBR', taskList[2].Type);
        system.assertEquals('SBR', taskList[3].Type);
        system.assertEquals('SBR', taskList[4].Type);
        system.assertEquals('SBR', taskList[5].Type);
        system.assertEquals('SBR', taskList[6].Type);
        system.assertEquals('SBR', taskList[7].Type);
        system.assertEquals('TCC', taskList[8].Type);
        system.assertEquals('TCC', taskList[9].Type);
        }
        Test.stopTest();
    }

  
    Static testMethod void checkBrochureRequest()
    {
       
        system.runAs(TestDataUtil.createUserRecord()) {
        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'AY', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '9988776666', '9988776666', '9988776666', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','APP','BR','karnataka',False,'India');
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        test.startTest();

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        test.stopTest();

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid FROM task where whatid in : opQuery ORDER BY type];
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
        system.debug('>>>>taskList'+taskList);
        //system.debug('>>>>taskList'+taskList.Type);
        system.assertEquals('SBR', taskList[0].Type);
        system.assertEquals('TCC', taskList[1].Type);
        //system.assertEquals('AY', opQuery[0].program__c);


    }
    }

    Static testMethod void checkDoNotCall()
    {
      system.runAs(TestDataUtil.createUserRecord()) {
        List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '9988776666', '9988776666', '9988776666', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',TRUE, 'India');
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        test.startTest();

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        test.stopTest();

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task>  taskList =[SELECT Type, WhatId, whoid FROM task where whatid in: opQuery ORDER BY type];
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
        system.debug('>>>>taskList'+taskList);
        system.assertEquals('SBR', taskList[0].Type);
        //system.assertEquals('ILSU', opQuery[0].Program__c);      
    }
    }

    Static testMethod void checkAddress()
    {
    
      system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest();
        List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'AY', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '9988776666', '9988776666', '9988776666', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','APP','BR','karnataka',false,'India');
        insert leadRecord;
        Event eventList =[SELECT Type,Program__c, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);
        system.assertEquals('AY', eventList.Program__c);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid FROM task where whatid in: opQuery ORDER BY type];
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
        system.debug('>>>>opQuery'+opQuery);

        system.debug('>>>>taskList'+taskList);
        system.assertEquals('SBR', taskList[0].Type);
        system.assertEquals('TCC', taskList[1].Type);
        test.stopTest();
    }
    
    }

    Static testMethod void checkPhone()
    {
     system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest();
        List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '', '', '', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

       

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


       

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid FROM task where whatid in: opQuery ORDER BY type];
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);                    
        List<Event> eventsList = TestDataUtil.createEvents(opQuery);
        System.debug('new event list>>>>>'+eventsList);
        insert eventsList;
        System.debug('new event list'+eventsList);
        system.assertEquals('SBR', taskList[0].Type);
        system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
        test.stopTest();
    }
    }

   
    Static testMethod void checkClosedSBR()
    {
      system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest();     
     List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSH', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '', '', '', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid,status FROM task where whatid in: opQuery ORDER BY type];
        List<Task> addingTask= new List<Task>();
        for(Task taskRecord: taskList){
        taskRecord.status='completed';
        taskRecord.isclosed__c=true;
        addingTask.add(taskRecord);
        }
        update addingTask;
        system.debug('addingTask>>>>>'+addingTask);
                
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
                     
        List<Event> eventsList = TestDataUtil.createEvents(opQuery);
        System.debug('new event list>>>>>'+eventsList);
        insert eventsList;
        System.debug('new event list'+eventsList);
       // system.assertnotEquals('SBR', taskList[0].Type);
        //system.assertEquals('SBR', taskList[0].Type);
        system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
       test.stopTest();

    }
    }
    Static testMethod void checkCallDone()
    {
        Map<String,TaskSettings__mdt> TaskSettingMap=MetaDataSelector.getTaskSettingMetada(); 
        system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest(); 
      List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '5689632140', '1234520123', '6574896321', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid,status FROM task where whatid in: opQuery ORDER BY type];
        List<Task> addingTask= new List<Task>();
        for(Task taskRecord: taskList){
        if(taskRecord.type=='TCC'){
        taskRecord.ActivityDate= Utility.ConvertDateTimeTodate(Datetime.now());
        addingTask.add(taskRecord);
        }
        
        }
        update addingTask;
                
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);               
        List<Event> eventsList = TestDataUtil.createEvents(opQuery);
        System.debug('new event list>>>>>'+eventsList);
        insert eventsList;
        System.debug('new event list>>>>2'+eventsList);
       // system.assertEquals('SBR', taskList[0].Type);
       List<Task> tasksList =[select id,type from task where id in : taskList order by type ];
       System.assertEquals(tasksList.size(),2);
       system.assertEquals('SBR', tasksList[0].Type);
       system.assertEquals('TCC', tasksList[1].Type);
        //system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
    test.stopTest();

    }
    }
    
     Static testMethod void checkSBR()
    {
      system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest();     
     List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '', '', '', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid,status FROM task where whatid in: opQuery ORDER BY type];
        List<Task> addingTask= new List<Task>();
        for(Task taskRecord: taskList){
        taskRecord.status='completed';
        taskRecord.isclosed__c=true;
        addingTask.add(taskRecord);
        }
        update addingTask;
        system.debug('addingTask>>>>>'+addingTask);
                
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);
                     
        List<Event> eventsList = TestDataUtil.createEvents(opQuery);
        System.debug('new event list>>>>>'+eventsList);
        insert eventsList;
        System.debug('new event list'+eventsList);
       system.assertEquals('SBR', taskList[0].Type);
        //system.assertEquals('SBR', taskList[0].Type);
        system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
       test.stopTest();

    }
    }
    Static testMethod void checkCallTypeClosed()
    {
       
       system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest(); 
      Map<String,TaskSettings__mdt> TaskSettingMap=MetaDataSelector.getTaskSettingMetada(); 
      List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '5689632140', '1234520123', '6574896321', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid,status FROM task where whatid in: opQuery ORDER BY type];
        List<Task> addingTask= new List<Task>();
        for(Task taskRecord: taskList){
        if(taskRecord.type=='TCC'){
        taskRecord.status='Completed';
        taskRecord.isclosed__c=True;
        addingTask.add(taskRecord);
        }
        
        }
        update addingTask;
                
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);               
        List<Event> eventsList = TestDataUtil.createEvents(opQuery);
        System.debug('new event list>>>>>'+eventsList);
        insert eventsList;
        System.debug('new event list>>>>2'+eventsList);
       // system.assertEquals('SBR', taskList[0].Type);
       List<Task> tasksList =[select id,type from task where id in : taskList order by type ];
       System.assertEquals(tasksList.size(),2);
       system.assertEquals('SBR', tasksList[0].Type);
       system.assertEquals('TCC', tasksList[1].Type);
        //system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
    test.stopTest();

    }
    }
    
    Static testMethod void checkPQ()
    {
       
       system.runAs(TestDataUtil.createUserRecord()) {
      test.startTest(); 
      Map<String,TaskSettings__mdt> TaskSettingMap=MetaDataSelector.getTaskSettingMetada(); 
      List<MarketProgramLevelSetting__c> newLeads = Test.loadData(MarketProgramLevelSetting__c.sObjectType, 'File_MarketProgramLevelSetting');

        Lead leadRecord = TestDataUtil.createDynamicLeads('Cole', 'Swain', 'Region', 'ILSU', 'DEB', ' DEB', 'street1', 'Bangalore', 'triton id123', '560048', '5689632140', '1234520123', '6574896321', system.today(),'StudentEmail1@email.com','StudentEmail2@email.com','ILS','BR','karnataka',false,'India'); 
        insert leadRecord;

        Event eventList =[SELECT Type, WhatId, whoid FROM event where whoid =: leadRecord.id];
        system.debug('>>>Type'+eventList.Type);

        

        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(leadRecord.id);

        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());

        lc.setOpportunityName('Cole Swain');


        

        List<opportunity> opQuery = [SELECT id, name,Program__c  FROM opportunity WHERE name = 'Cole Swain'];
        List<Task> taskList =[SELECT Type, WhatId, whoid,status FROM task where whatid in: opQuery ORDER BY type];
        List<Task> addingTask= new List<Task>();
        for(Task taskRecord: taskList){
        if(taskRecord.type=='TCC'){
        //taskRecord.status='Completed';
        //taskRecord.isclosed__c=True;
        addingTask.add(taskRecord);
        }
        
        }
        update addingTask;
                
        system.debug('>>>>opQuery'+opQuery);
        List<Id> Ids=new List<Id>();
        for( Opportunity oppRecord:opQuery)
        {
            Ids.add(oppRecord.Id);
        }
        TasksHelper.convertActivitiesToTask( Ids);               
         List<Event> eventsList = new List <Event>();
        for(Opportunity opp: opQuery)
        {
            Event eventRecord = new Event();
            eventRecord.Subject='test';
            eventRecord.StartDateTime=system.now();
            eventRecord.EndDateTime=system.today().adddays(4);
            eventRecord.whatid=opp.id;
            eventRecord.Type='PQ';
            eventsList.add(eventRecord);
        }
        insert eventsList;
        System.debug('new event list>>>>2'+eventsList);
       // system.assertEquals('SBR', taskList[0].Type);
       List<Task> tasksList =[select id,type from task where id in : taskList order by type ];
       System.assertEquals(tasksList.size(),2);
      // system.assertEquals('SBR', tasksList[0].Type);
      // system.assertEquals('TCC', tasksList[1].Type);
        //system.debug('>>>>taskList'+taskList);
       // system.assertEquals('ILSU', opQuery[0].Program__c);
    test.stopTest();

    }
    }
        
}